import '@fontsource-variable/lexend';
import '@fontsource-variable/unbounded';

const designs=[
  {id:'ticket',title:'Ticket S',font:'bricolage',name:'Pupside',description:'A notched trading ticket with a clear S cut through it. Rounded, characterful lettering keeps it welcoming.',note:'Bricolage Grotesque · 800',recommendation:'My pick for the game. The ticket belongs to your interaction language, and the softer lettering sits naturally beside RoboPup.',mark:'<path fill="var(--mark)" d="M15 6H49a7 7 0 0 1 7 7v12a7 7 0 0 0 0 14v12a7 7 0 0 1-7 7H15a7 7 0 0 1-7-7V39a7 7 0 0 0 0-14V13a7 7 0 0 1 7-7Z"/><path class="mark-detail" d="M41 21H28a6 6 0 0 0 0 12h8a6 6 0 0 1 0 12H23" fill="none" stroke="var(--cut)" stroke-width="6" stroke-linecap="square"/>'},
  {id:'bell',title:'Closing bell',font:'sora',name:'Pupside',description:'The bell becomes the signature. A low, wide silhouette paired with friendly lowercase lettering.',note:'Sora · 750',recommendation:'The warmest direction. It connects the brand to the five-day ritual and the mascot’s bell. Its tradeoff: the mark is less specifically about tickets.',mark:'<g class="bell-body"><path fill="var(--mark)" d="M28 15h8v8c12 2 20 12 20 25H8c0-13 8-23 20-25Z"/><rect x="23" y="9" width="18" height="6" rx="3" fill="var(--mark)"/><path d="M17 42c1-7 5-12 11-14" fill="none" stroke="var(--cut)" stroke-width="4" stroke-linecap="round"/></g><rect x="4" y="51" width="56" height="7" rx="3.5" fill="var(--mark)"/>'},
  {id:'stamp',title:'Desk stamp',font:'space',name:'STRIKE <em>DESK</em>',description:'A compact SD monogram with a clipped-corner frame. Tighter, quieter lettering gives the desk a more editorial feel.',note:'Space Grotesk · 700 / 400',recommendation:'The most restrained direction. Strong in a navigation bar or app icon, with a little less of the arcade personality.',mark:'<path class="stamp-frame" d="M10 6h36l12 12v36a4 4 0 0 1-4 4H10a4 4 0 0 1-4-4V10a4 4 0 0 1 4-4Z" fill="none" stroke="var(--mark)" stroke-width="4"/><path d="M27 22h-7a5 5 0 0 0 0 10h2a5 5 0 0 1 0 10h-7M36 22v20h4c12 0 12-20 0-20Z" fill="none" stroke="var(--mark)" stroke-width="4.5" stroke-linecap="square" stroke-linejoin="round"/>'}
];
const mark=design=>`<svg class="brand-mark" viewBox="0 0 64 64" aria-hidden="true">${design.mark}</svg>`;
const lockup=design=>`<div class="lockup" role="img" aria-label="Pupside ${design.title} logo">${mark(design)}<span class="brand-name" aria-hidden="true">${design.name}</span></div>`;
document.getElementById('studies').innerHTML=designs.map(design=>`<section class="brand-study ${design.id}" id="${design.id}"><div class="study-heading"><h2>${design.title}</h2><p>${design.description}</p></div><div class="identity" data-font="${design.font}"><div class="hero-specimen">${lockup(design)}<span class="specimen-note">${design.note}<br>Proposed pairing</span></div><div class="type-controls"><label>Try a typeface <select aria-label="Typeface for ${design.title}"><option value="bricolage" ${design.font==='bricolage'?'selected':''}>Bricolage Grotesque</option><option value="sora" ${design.font==='sora'?'selected':''}>Sora</option><option value="space" ${design.font==='space'?'selected':''}>Space Grotesk</option></select></label><button data-replay="${design.id}">Replay arrival</button></div><div class="header-specimen">${lockup(design)}<div class="header-data"><div><span>Time left</span><strong>12:20</strong></div><div><span>Total worth</span><strong>$1,000,000</strong></div></div></div><div class="scale-strip"><div class="icon-sizes">${[16,24,40,64].map(size=>`<div class="icon-size" style="--size:${size}px">${mark(design)}<span>${size}px</span></div>`).join('')}</div><div class="light-specimen">${lockup(design)}</div></div></div><p class="recommendation">${design.recommendation}</p></section>`).join('');
const motions=new Map();
function replay(id){motions.get(id)?.forEach(m=>m.cancel());const section=document.getElementById(id);const icon=section.querySelector('.hero-specimen .brand-mark');const word=section.querySelector('.hero-specimen .brand-name');const frames=id==='ticket'?[{transform:'translateY(-7px) rotate(-6deg)',opacity:.3},{transform:'none',opacity:1}]:id==='bell'?[{transform:'rotate(0)'},{transform:'rotate(-7deg)',offset:.25},{transform:'rotate(4deg)',offset:.55},{transform:'none'}]:[{transform:'scale(1.12)',opacity:.3},{transform:'scale(1)',opacity:1}];motions.set(id,[icon.animate(frames,{duration:id==='bell'?600:430,easing:'cubic-bezier(.16,1,.3,1)'}),word.animate([{opacity:.25},{opacity:1}],{duration:330,delay:60,fill:'backwards'})]);}
document.querySelectorAll('[data-replay]').forEach(button=>button.addEventListener('click',()=>replay(button.dataset.replay)));
document.querySelectorAll('.type-controls select').forEach(select=>select.addEventListener('change',()=>{select.closest('.identity').dataset.font=select.value;}));
document.getElementById('replay').addEventListener('click',()=>designs.forEach(design=>replay(design.id)));
for(const [id,className] of [['mobile','mobile-preview'],['mono','mono']])document.getElementById(id).addEventListener('click',event=>{event.currentTarget.setAttribute('aria-pressed',String(document.body.classList.toggle(className)));});
window.addEventListener('pagehide',()=>motions.forEach(list=>list.forEach(m=>m.cancel())),{once:true});
